### ISSUE TITLE
xcode-version 12.0 points to Xcode 12.2 beta

### ISSUE THREAD

**Issue by JonnyBeeGod** [maxim-lobanov/setup-xcode#8] opened 2020-10-04 14:30 UTC
I am using the following configuration: 

```
steps:
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.0

```
This leads to the action using Xcode 12.2:
<img width="391" alt="Bildschirmfoto 2020-10-04 um 16 27 34" src="https://user-images.githubusercontent.com/2844335/95018222-8e5bb780-065e-11eb-954c-23caa00f0083.png">

This is wrong as I expect the action using Xcode 12.0 as specified. 

Workaround: latest-stable does use Xcode 12.0 as expected

**Comment by maxim-lobanov** [comment] 2020-10-04 16:56
Hello @JonnyBeeGod ! Thank you for reporting!

I was able to reproduce this issue from my side. Based on my investigation, it is an issue with parsing YAML on GitHub Actions side rather than issue with this action. When you pass `12.0` as task input, `.0` is trimmed by GH and value is passed just as `12`.
![image](https://user-images.githubusercontent.com/16715858/95021401-72b1da80-0679-11eb-930a-7c98a8617901.png)
![image](https://user-images.githubusercontent.com/16715858/95021406-78a7bb80-0679-11eb-98a1-fc02601e552c.png)
Based on this input, action works as expected. If you pass `12`, it selects the latest Xcode `12.x`. It is `12.2.0`

A few interesting examples below:
- if you pass version `xcode-version: 12` - the value come to task as string `12`
- if you pass version `xcode-version: 12.0` - the value come to task as string !!! `12` too.
- if you pass version `xcode-version: 12.0.0` - the value come to task as string `12.0.0` as expected.
- if you pass version `xcode-version: '12.0'` - the value come to task as string `12.0` as expected.

I am not familiar with YAML specification to say whether it is a bug or expected behavior. Looks like
- If quotes are used `'12.0'` it is clear that it is a string and shouldn't be cut.
- If quotes are not used, value is interpreted as a number, so it sounds logical that `12.0` is parsed as `12.0`. `12.0.0` can't be interpreted as string, so it is kept as string without cutting.

I see a few options to unblock you:
1) use `xcode-version: '12.0'`
2) use `xcode-version: 12.0.0`

**Comment by JonnyBeeGod** [comment] 2020-10-04 17:13
Hey @maxim-lobanov thx for the quick analysis! I guess it makes sense to use the correct types for the parameter and not rely on type casting behavior.

So as you said the action does work as expected but I would suggest to update the examples in README.MD

**Comment by maxim-lobanov** [comment] 2020-10-05 06:46
That makes sense. I have updated docs #9 .

**Comment by maxim-lobanov** [comment] 2020-10-06 09:44
@JonnyBeeGod , I am closing the issue. Please let me know if you have any concerns

**Closed by maxim-lobanov** 2020-10-06 09:44 UTC

**Comment by JonnyBeeGod** [comment] 2020-10-06 16:13
sure, all good. Thanks for responding so fast!
